[build]
  cmd = "go build -o main ."
  bin = "main"
  exclude_dir = ["node_modules"]
  include_ext = ["go", "toml", "yaml"]
  kill_delay = "25ms"
  log = "air_log.log"
  poll = false
  stop_on_error = false

[log]
  timeformat = "2006-01-02T15:04:05Z07:00"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "blue"
  runner = "green"
  app = "default"
  error = "red"

[misc]
  clean_on_exit = false