basePath: /api
definitions:
  dto.CreateProductDto:
    properties:
      category:
        example: Electronics
        type: string
      city:
        example: São Paulo
        type: string
      description:
        example: A great smartphone
        type: string
      image:
        example: smartphone.jpg
        type: string
      postal_code:
        example: 12345-678
        type: string
      price:
        example: 999.99
        type: number
      state:
        example: SP
        type: string
      title:
        example: Smartphone
        type: string
    required:
    - category
    - price
    - title
    type: object
  models.Category:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.Product:
    properties:
      category:
        $ref: '#/definitions/models.Category'
      category_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      image:
        type: string
      price:
        type: number
      slug:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: suporte@exhibitly.com
    name: Suporte Exhibitly
    url: http://exhibitly.com/support
  description: API de classificados online para o projeto Exhibitly.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: http://exhibitly.com/terms/
  title: Exhibitly API
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Cria um novo produto com base nos dados fornecidos
      parameters:
      - description: Detalhes do Produto
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/dto.CreateProductDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
      summary: Criação de produto
      tags:
      - Products
swagger: "2.0"
